# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoQr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('fecha_expiracion', models.DateTimeField(null=True)),
                ('estado', models.CharField(max_length=1)),
                ('hashPrivado', models.DecimalField(decimal_places=0, max_digits=60)),
                ('hashVerificacion', models.DecimalField(decimal_places=0, max_digits=60)),
                ('opciones', models.CharField(max_length=10)),
                ('dias', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CodigoQr')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CodigoQr')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CodigoQr')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaQr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField()),
                ('codigoqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CodigoQr')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('url', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='QrMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('urlMusica', models.TextField()),
                ('codigoqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CodigoQr')),
            ],
        ),
        migrations.CreateModel(
            name='QrPlantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CodigoQr')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('enlaces', models.TextField()),
                ('codigo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=60)),
                ('contrasena', models.TextField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=60)),
                ('contrasena', models.TextField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='usuariovendedor',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vendedor'),
        ),
        migrations.AddField(
            model_name='codigovendedor',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vendedor'),
        ),
        migrations.AddField(
            model_name='codigousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='codigotema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tema'),
        ),
    ]
